<?php  defined('SYSPATH') or die("No direct script access.");
//define base url
DEFINE('PROTOCOL','http');
DEFINE('URL_BASE',url::base(PROTOCOL,true));
//Number limit
DEFINE("NUMBER_FORMAT_LIMIT",2);
DEFINE("SERVER_DATE",date('Y-m-d H:i:s'));
//for Date
DEFINE('SERVER_TIME_FORMAT',"h:i:s A");
DEFINE('CHECKING_TIME',"5");

//For defining height and width for videos in my gigs page
//========================================================
DEFINE('TESTIMONIALS_VIDEO_WIDTH',"450");
DEFINE('TESTIMONIALS_VIDEO_HEIGHT',"250");
DEFINE('TESTIMONIALS_IMAGE_WIDTH',"200");
DEFINE('TESTIMONIALS_IMAGE_HEIGHT',"200");
//Admin Site pagination page number
DEFINE('ADM_PER_PAGE',"15");
//img folder path defined
//========================
DEFINE('PAGE_NO',1);
DEFINE('REC_PER_PAGE',10);
DEFINE('REC_CLO_PAGE',"10");
DEFINE('PUBLIC_FOLDER',"public");
DEFINE('UPLOADED_FILES',"uploaded_files");

//bread crumb link default home page link - Dashboard
DEFINE("HOME","dashboard/index");
//If the amount is null, will define amount as 0
DEFINE('DOCUMENT_ROOT',"views/themes/");
DEFINE("ZERO_VALUE","0");
DEFINE('USERS_IMGFOLDER',"users/full_50x50/");
DEFINE('USERS_THUMB_IMGFOLDER',"users/thumb_10x10/");
DEFINE('ACTIVE',"A");
DEFINE('FEATURE',"F");
DEFINE('IN_ACTIVE',"I");
DEFINE('DELETED_STATUS',"D");
DEFINE('ENABLE',"E");
DEFINE('DISABLE',"D");
DEFINE('USER',"N");
DEFINE('ADMIN',"A");
DEFINE('YES',"Y");
DEFINE('NO',"N");
DEFINE('SUCESS',"1");
DEFINE('RESUMES',"R");
DEFINE('HOLD',"H");
DEFINE('LIVE',"L");
DEFINE('FUTURE',"F");
DEFINE('FEATURED',"F");
DEFINE('NONE',"N");
DEFINE('HOT',"H");
DEFINE('READ',"R");
DEFINE('UNREAD',"U");
DEFINE('CLOSED',"C");
DEFINE('UNSOLD',"Z");
DEFINE('SOLD',"S");
DEFINE('FAIL',"0");
DEFINE('BLOCK',"1");
DEFINE('UNBLOCK',"0");
DEFINE('SUCCESS',"S");
DEFINE('OFFLINE',"O");
DEFINE("USERPROFILE","/users/login/");
DEFINE("USERACTIVATION","users/activation/");
DEFINE("RANDOM_KEY_LENGTH","20");
DEFINE('PRODUCTS_IMGFOLDER',"products/");
DEFINE('SITE_LOGOIMGFOLDER',"site_logo/");
DEFINE('USER_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.USERS_IMGFOLDER);
DEFINE('USER_IMGPATH_THUMB',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.USERS_THUMB_IMGFOLDER);
DEFINE('PRODUCTS_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.PRODUCTS_IMGFOLDER);
DEFINE('PRODUCTS_IMGPATH_THUMB',PRODUCTS_IMGPATH.'thumb/');
DEFINE('PRODUCTS_IMGPATH_THUMB1',PRODUCTS_IMGPATH.'thumb1/');
DEFINE('PRODUCTS_IMGPATH_THUMB2',PRODUCTS_IMGPATH.'thumb2/');
DEFINE('PRODUCTS_IMGPATH_THUMB3',PRODUCTS_IMGPATH.'thumb3/');//For Black theme(beginner,penny and peak)Product details only
DEFINE('PRODUCTS_IMGPATH_THUMB4',PRODUCTS_IMGPATH.'thumb4/');
DEFINE('PRODUCTS_IMGPATH_THUMB5',PRODUCTS_IMGPATH.'thumb5/');
DEFINE('PRODUCTS_IMGPATH_THUMB6',PRODUCTS_IMGPATH.'thumb6/');
DEFINE('PRODUCTS_IMGPATH_THUMB81x54',PRODUCTS_IMGPATH.'thumb81x54/');
DEFINE('PRODUCTS_IMGPATH_THUMB150x150',PRODUCTS_IMGPATH.'thumb150x150/');
DEFINE('LOGO_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.SITE_LOGOIMGFOLDER);
//DEFINE('CSSPATH',ROOT."/".CSSTHEME.'/css/');
DEFINE('SCRIPTPATH',URL_BASE.'public/js/');
DEFINE('SCRIPTPATH_DATE','/public/datetime/');
//DEFINE('IMGPATH',ROOT.'/'.CSSTHEME.'/images/');
DEFINE('TESTIMONIALS_IMGFOLDER',"testimonials/");
DEFINE('TESTIMONIALS_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.TESTIMONIALS_IMGFOLDER);
DEFINE('BANNER_IMGFOLDER',"banner/");
DEFINE('BANNER_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.BANNER_IMGFOLDER);
DEFINE('LIGHTBOX_SCRIPTPATH','public/lightbox/js/jquery.lightbox-0.5.js');
DEFINE('LIGHTBOX_CSSPATH','public/lightbox/css/jquery.lightbox-0.5.css');

//default no image 
//=================
DEFINE('NO_IMAGE','no_img.png');
DEFINE('USER_NO_IMAGE','bidder_img.png');
DEFINE('USER_NO_IMAGE2','default_user.png');
DEFINE('DEFAULT_LOGO_IMAGE','logo.png');
DEFINE('SITE_LOGO_IMAGE','action-logo.png');

//users small thumb image
//=======================
DEFINE('USER_SMALL_IMAGE_WIDTH',"97");
DEFINE('USER_SMALL_IMAGE_HEIGHT',"75");
DEFINE('USER_SMALL_IMAGE_WIDTH_20x20',"20");
DEFINE('USER_SMALL_IMAGE_HEIGHT_20x20',"20");

//banner small thumb image
//=======================
DEFINE('BANNER_SMALL_IMAGE_WIDTH',"97");
DEFINE('BANNER_SMALL_IMAGE_HEIGHT',"75");
DEFINE('BANNER_RESIZE_IMAGE_WIDTH',"680");
DEFINE('BANNER_RESIZE_IMAGE_HEIGHT',"200");

//logo small thumb image
//=======================
DEFINE('LOGO_SMALL_IMAGE_WIDTH',"184");
DEFINE('LOGO_SMALL_IMAGE_HEIGHT',"61");

//Calendar Icon Image
//===================
DEFINE('CALENDAR_ICON_PATH',URL_BASE.'public/admin/images/calendar.png');
//For Work status -Dashboard
//=========================
DEFINE('WORK_ACTIVE',"A");
DEFINE('WORK_SUSPEND',"Y");
DEFINE('WORK_ALL',"ALL");

//VIDEO URL CONTENT
DEFINE('YOUTUBE_VIDEO_URL',"http://www.youtube.com/watch?v=");

//FOR Mail sending host
//=====================
DEFINE('HOST_HTTPS',"https://");
DEFINE('HOST_HTTP',"http://");
DEFINE('PORT',"443");

//For Defining Recent category id
DEFINE("RECENT_CAT","78");

//more action flash
//==================
DEFINE('DELETE_ACTION',"del");
DEFINE('ACTIVE_ACTION',"active");
DEFINE('INACTIVE_ACTION',"inactive");

//Email Variables
DEFINE("SITE_NAME","##SITE_NAME##");
DEFINE("USERNAME","##USERNAME##");
DEFINE("FROM_EMAIL","##FROM_EMAIL##");
DEFINE("CONTACT_MAIL","##CONTACT_MAIL##");
DEFINE("SITE_URL","##SITE_URL##");
DEFINE("ACTIVATION_URL","##ACTIVATION_URL##");
DEFINE("PASSWORD","##PASSWORD##");
DEFINE("TELEPHONE","##TELEPHONE##");
DEFINE("FIRST_NAME","##FIRST_NAME##");
DEFINE("LAST_NAME","##LAST_NAME##");
DEFINE("SUBJECT","##SUBJECT##");
DEFINE("POST_DATE","##POST_DATE##");
DEFINE("CONTACT_URL","##CONTACT_URL##");
DEFINE("IP","##IP##");
DEFINE("SITE_ADDR","##SITE_ADDR##");
DEFINE("SITE_LINK","##SITE_LINK##");
DEFINE("FROM_URL","##FROM_URL##");
DEFINE("LOGIN_LABEL","##LOGINLABEL##");
DEFINE("MESSAGE","##MESSAGE##");
DEFINE("TO_MAIL","##TO_MAIL##");
DEFINE("NEW_PASSWORD","##NEW_PASSWORD##");
DEFINE("USEDTOLOGIN","##USEDTOLOGIN##");
DEFINE("PRODUCTNAME","##PRODUCTNAME##");
DEFINE("PRODUCTCOST","##PRODUCTCOST##");
DEFINE("CURRENTPRICE","##CURRENTPRICE##");
DEFINE("SAVEAMOUNT","##SAVEAMOUNT##");
DEFINE("EMAIL","##EMAIL##");
//config for site name and from email
//===================================
DEFINE("AUCTION_SCRIPT","AUCTION SCRIPT");
DEFINE("SEND_MAIL_TRUE","1");
DEFINE("MAIL_SUCCESS","1");
DEFINE("MAIL_UNSUCCESS","0");
DEFINE("MAIL_SUCCESS_SUB","0");

//Email id confic
//DEFINE('ADMIN_USER_ADD',6);
//DEFINE('ADMIN_USER_DELETE',7);
//DEFINE('ADMIN_USER_ACTIVE',8);
//DEFINE('ADMIN_USER_DEACTIVATE',9);

//For User Login Type
//===================
DEFINE('NORMAL',"N");
DEFINE('FACEBOOK',"F");
DEFINE('TWITTER',"T");
define('LINKEDIN','L');
DEFINE('OPENID',"O");
DEFINE('ALL_USER',"A");
DEFINE("ADMIN_USER_TYPE","A");
//End Admin

//email template id config
//=========================
DEFINE('WELCOME_EMAIL',1);
DEFINE('FORGOT_PASSWORD',2);
DEFINE('CONTACT_AUTO_REPLY',4);
DEFINE('NEW_USER_JOIN',5);
DEFINE('CONTACT_US',6);
DEFINE('CONTACT_US_AUTO_REPLY',7);

DEFINE('ADMIN_USER_ADD',8);
DEFINE('ADMIN_USER_DELETE',9);
DEFINE('ADMIN_USER_ACTIVE',10);
DEFINE('ADMIN_USER_DEACTIVATE',11);
DEFINE('ADMIN_CHANGE_PASSWORD',12);
DEFINE('USER_CHANGE_PASSWORD',13);
DEFINE('WINNERS_REPLY',14);
DEFINE('NEWS_LATTERMANAGE',15);
DEFINE('ACTIVATION_REQUEST',16);
DEFINE('FACEBOOK_PASSWORD',17);

DEFINE('TWITTER_SIGNUP',18);
DEFINE('ACTIVATION_CODE_STATUS',"1");

//YAHOO SCRIPT (FOR JSON)
DEFINE('YAHOO_SCRIPTPATH','/public/js/yahoo-min.js');
//YAHOO JSON SCRIPT (FOR JSON)
DEFINE('YAHOO_JSON_SCRIPTPATH','/public/js/json-min.js');
//General Settings
//min length config
//min length config
DEFINE("MIN_ZERO",0);
DEFINE("ZERO",0);
DEFINE("MIN_ONE",1);
DEFINE("MIN_REDUCTION",10);

DEFINE("MIN_MAXCOUNTDOWN",10);
DEFINE("MIN_BIDCOUNTDOWN",5);
DEFINE("MIN_PAYPAL_CURRENCY_CODE",1);
DEFINE("MAX_PAYPAL_CURRENCY_CODE",3);
DEFINE('LIVE_MODE',"L");
DEFINE('TEST_MODE',"T");
DEFINE("MIN_PRICE_RANGE",1);
DEFINE("MAX_PRICE_RANGE",99);
DEFINE("MIN_LENGTH_RANGE",99);
DEFINE("MIN_COMPLETE_RANGE",20);
DEFINE("MAX_PACKAGES_RANGE",1);
//Transaction Logs Msg
DEFINE("TRANS_LOG_BUYER_PACKAGE_DESC","##BUYERNAME## bought ##PACKAGE_NAME## for ##AMOUNT##, order# ##ORDER_NO##");
DEFINE("PAYMENT_PACKAGE_TITLE","##PACKAGE_TITLE##");
DEFINE("CREDIT","C");
DEFINE("DEBIT","D");

//For package status in order
//=============================
DEFINE("SUCCESS_PAYMENT_ORDER_STATUS","PSA");
DEFINE("SUCCESS_PAYMENT_ORDER_ACTION","NOR");

//For package paid status
//========================
DEFINE("PAID_PENDING","PND");	
DEFINE("PAID_ACTIVE","ACT");
DEFINE("START_TIME","00:00:00");
DEFINE("END_TIME","23:59:59");
DEFINE('SITE_TITLE_CAPTION','Welcome to ');
DEFINE('TOTAL_NO_TABLES','43');
//ads small thumb image
//=======================
DEFINE('ADS_SMALL_IMAGE_WIDTH',"100");
DEFINE('ADS_SMALL_IMAGE_HEIGHT',"100");
DEFINE('ADS_RESIZE_IMAGE_WIDTH',"250");
DEFINE('ADS_RESIZE_IMAGE_HEIGHT',"250");

DEFINE('ADS_NOIMGPATH','public/uploaded_files/ads/noimageforad.jpg');
DEFINE('CAT_NO_IMAGE','ADS_NOIMGPATH');

DEFINE('ADS_IMGFOLDER',"ads/");
DEFINE('ADS_IMGPATH',PUBLIC_FOLDER.'/'.UPLOADED_FILES.'/'.ADS_IMGFOLDER);
DEFINE('ADS_NO_IMAGE','ads_no-image-found.jpg');
//selvam
DEFINE('SUBSCRIBER_EMAIL',21);
//VENKATRAJA
DEFINE("TRANS_LOG_ADD_PRODUCT_DESC","##BUYERNAME## pays  ##AMOUNT## for listing the  product   ##PRODUCT_NAME## ");
DEFINE("ADD_PRODUCT","A");
DEFINE("BUY_PRODUCT","B");
DEFINE("USER_REGISTER","U");
DEFINE("TRANS_LOG_SELLER_PRODUCT_DESC","##SELLERNAME## credits the amount ##AMOUNT## for the sold product ##PRODUCT_NAME##, order# ##ORDER_NO##");
?>
